title: Tech Interview Coach | FAQs
description: All the docs you need for Tech Interview Coaching.
theme: just-the-docs

url: https://techinterview.coach/faq

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"